{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "koptimizer.serviceAccountName" . }}
  labels:
    {{- include "koptimizer.labels" . | nindent 4 }}
  annotations:
    {{- if and (eq .Values.config.cloudProvider "aws") .Values.cloudConfig.aws.roleArn }}
    eks.amazonaws.com/role-arn: {{ .Values.cloudConfig.aws.roleArn | quote }}
    {{- end }}
    {{- if and (eq .Values.config.cloudProvider "gcp") .Values.cloudConfig.gcp.workloadIdentityServiceAccount }}
    iam.gke.io/gcp-service-account: {{ .Values.cloudConfig.gcp.workloadIdentityServiceAccount | quote }}
    {{- end }}
    {{- if and (eq .Values.config.cloudProvider "azure") .Values.cloudConfig.azure.workloadIdentityClientID }}
    azure.workload.identity/client-id: {{ .Values.cloudConfig.azure.workloadIdentityClientID | quote }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
